const $ = id => document.getElementById(id);
const state = { outdoor: [], indoor: [], activeLocations: [], lastRoute: null };
const label = l => l.name || `${l.roomName} [${l.buildingName}, floor ${l.floor}]`;
const escapeHtml = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url, options={}) { const r = await fetch(url, {headers:{'Content-Type':'application/json'}, ...options}); const data = await r.json(); if (!r.ok || data.error) throw new Error(data.error || `Request failed (${r.status})`); return data; }
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function activeItems(){return $('indoorMode').checked ? state.indoor : state.outdoor}
function fillSelect(el, items, placeholder){const old=el.value;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(l=>`<option value="${escapeHtml(label(l))}">${escapeHtml(label(l))}</option>`).join('');if(items.some(l=>label(l)===old))el.value=old}
function refreshPlanner(){state.activeLocations=activeItems();fillSelect($('source'),state.activeLocations,'Choose starting point');fillSelect($('destination'),state.activeLocations,'Choose destination');const pathItems=document.querySelector('input[name="scope"]:checked')?.value==='indoor'?state.indoor:state.outdoor;fillSelect($('pathA'),pathItems,'Choose location A');fillSelect($('pathB'),pathItems,'Choose location B');}
async function loadLocations(){const d=await api('/api/locations');state.outdoor=d.outdoor||[];state.indoor=d.indoor||[];refreshPlanner();renderLocations();renderMap();$('connectionText').textContent='Connected to C++ backend';$('locationCount').textContent=`${state.outdoor.length+state.indoor.length} locations`}
function renderLocations(){const q=$('locationSearch').value.toLowerCase();const all=[...state.outdoor.map(x=>({...x,kind:'Outdoor'})),...state.indoor.map(x=>({...x,kind:'Indoor'}))].filter(x=>label(x).toLowerCase().includes(q)||(x.type||'').toLowerCase().includes(q)||(x.kind||'').toLowerCase().includes(q));$('locationList').innerHTML=all.length?all.map(l=>`<div class="location-item"><div class="location-icon">${l.kind==='Indoor'?'▦':'⌖'}</div><div><b>${escapeHtml(label(l))}</b><small>${escapeHtml(l.kind)} · ${escapeHtml(l.type||'Room')}</small></div></div>`).join(''):'<p class="muted">No matching locations.</p>';}
function renderMap(path=[]){const box=$('campusMap');const points=state.outdoor.slice(0,28);if(!points.length){box.innerHTML='<div class="map-loading">No outdoor locations available.</div>';return}box.innerHTML='';const coords=points.map((l,i)=>({l,x:8+(i%5)*21+(Math.floor(i/5)%2)*5,y:16+Math.floor(i/5)*21}));coords.forEach((p,i)=>{if(i<coords.length-1){const n=coords[i+1],dx=(n.x-p.x)*box.clientWidth/100,dy=(n.y-p.y)*box.clientHeight/100;const line=document.createElement('div');line.className='map-edge';line.style.left=p.x+'%';line.style.top=p.y+'%';line.style.width=Math.hypot(dx,dy)+'px';line.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;box.appendChild(line)}});coords.forEach((p,i)=>{const b=document.createElement('button');b.className='map-node'+(path.includes(p.l.name)?' selected':'');b.style.left=p.x+'%';b.style.top=p.y+'%';b.textContent=p.l.name;b.title=p.l.name;b.onclick=()=>{if(!$('indoorMode').checked){$('source').value=p.l.name;toast(`Starting point set to ${p.l.name}`)}};box.appendChild(b)});}
function renderRoute(result){state.lastRoute=result;$('resultHeading').textContent=result.found?'Route ready':'No route found';if(!result.found){$('routeResult').innerHTML=`<div class="empty-result"><div class="empty-illustration">↯</div><b>No accessible route found</b><p>${escapeHtml(result.message||'Try a different destination or check blocked pathways.')}</p></div>`;return}if(result.comparison){$('routeResult').innerHTML=result.routes.map(r=>`<div class="compare-item"><strong>${escapeHtml(r.algorithm)}</strong><p>${r.found?`${escapeHtml((r.path||[]).join(' → '))}<br>${Number(r.distance).toFixed(1)} m · ${Number(r.walkingTime).toFixed(1)} min`:'No accessible path found'}</p></div>`).join('');renderMap(result.routes.find(r=>r.algorithm==='Dijkstra')?.path||[]);return}const steps=result.path||[];$('routeResult').innerHTML=`<div class="route-summary"><div class="metric"><span>DISTANCE</span><strong>${Number(result.distance).toFixed(0)}<small> m</small></strong></div><div class="metric"><span>EST. WALK</span><strong>${Number(result.walkingTime).toFixed(1)}<small> min</small></strong></div></div><ol class="route-steps">${steps.map((s,i)=>`<li><span class="step-dot">${i===0?'●':i===steps.length-1?'✓':i+1}</span><div><b>${escapeHtml(s)}</b><small>${i===0?'Starting point':i===steps.length-1?'Destination':'Continue along accessible pathway'}</small></div></li>`).join('')}</ol><p class="microcopy">Algorithm: ${escapeHtml(result.algorithm||'Dijkstra')} · Accessible links only</p>`;renderMap(steps)}
async function findRoute(emergency=false){const source=$('source').value,destination=$('destination').value;if(!source){toast('Choose your current location first.');return}if(!emergency&&!destination){toast('Choose a destination.');return}if(!emergency&&source===destination){toast('Choose two different locations.');return}if(emergency&&$('indoorMode').checked){toast('Emergency exit routing currently uses the outdoor campus network.');return}const btn=$('findRouteBtn');btn.disabled=true;btn.textContent=emergency?'Finding nearest exit…':'Finding route…';try{const mode=emergency?'emergency':($('indoorMode').checked?'indoor':'outdoor');const algorithm=document.querySelector('input[name="algorithm"]:checked').value;const q=new URLSearchParams({source,destination:destination||'',mode,algorithm});const d=await api('/api/route?'+q.toString());renderRoute(d);if(d.found)toast('Accessible route calculated.')}catch(e){toast(e.message);$('routeResult').innerHTML=`<div class="empty-result"><b>Could not calculate route</b><p>${escapeHtml(e.message)}</p></div>`}finally{btn.disabled=false;btn.innerHTML='Find accessible route <span>→</span>'}}
async function loadHistory(){try{const d=await api('/api/history');const lines=d.items||[];$('historyList').innerHTML=lines.length?lines.slice().reverse().map(line=>{const parts=line.split('|').map(s=>s.trim());return `<div class="history-item"><div><b>${escapeHtml(parts[0]||'Saved route')}</b><small>${escapeHtml(parts[1]||line)}</small></div><span class="history-distance">${escapeHtml(parts[2]||'')}</span></div>`}).join(''):'<p class="muted">No saved routes yet. Find a route to start building your history.</p>'}catch(e){$('historyList').innerHTML=`<p class="muted">${escapeHtml(e.message)}</p>`}}
async function pathway(action){const scope=document.querySelector('input[name="scope"]:checked').value,source=$('pathA').value,destination=$('pathB').value;if(!source||!destination||source===destination){toast('Choose two different locations.');return}try{const d=await api('/api/pathway',{method:'POST',body:JSON.stringify({scope,source,destination,action})});$('manageMessage').className='notice';$('manageMessage').textContent=d.message;toast(d.message);await loadLocations()}catch(e){$('manageMessage').className='notice error';$('manageMessage').textContent=e.message;$('manageMessage').classList.remove('hidden');toast(e.message)}}
function showView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={navigate:'Find your way.',locations:'Know your campus.',manage:'Keep routes up to date.',history:'Your journeys, saved.'};$('pageTitle').textContent=titles[view]||titles.navigate;if(view==='history')loadHistory()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('findRouteBtn').addEventListener('click',()=>findRoute(false));$('emergencyBtn').addEventListener('click',()=>findRoute(true));$('refreshBtn').addEventListener('click',async()=>{try{await loadLocations();await loadHistory();toast('Campus data refreshed.')}catch(e){toast(e.message)}});$('swapBtn').addEventListener('click',()=>{const s=$('source').value; $('source').value=$('destination').value; $('destination').value=s});$('indoorMode').addEventListener('change',()=>{refreshPlanner();$('campusMap').innerHTML='<div class="map-loading">Switch to outdoor mode to view the campus overview.</div>'});$('locationSearch').addEventListener('input',renderLocations);$('historyRefresh').addEventListener('click',loadHistory);$('blockBtn').addEventListener('click',()=>pathway('block'));$('unblockBtn').addEventListener('click',()=>pathway('unblock'));document.querySelectorAll('input[name="scope"]').forEach(el=>el.addEventListener('change',refreshPlanner));
loadLocations().then(loadHistory).catch(e=>{$('connectionText').textContent='Backend not connected';toast('Start the CampusNavX GUI server using run_gui.bat')});
